# Generated by Django 2.2.7 on 2019-12-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_reg',
            fields=[
                ('user_email', models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('user_password', models.CharField(max_length=55)),
                ('user_name', models.CharField(max_length=55)),
                ('user_phone', models.CharField(max_length=55)),
            ],
        ),
    ]
